---
include:
  - board: corne_choc_pro_left
    snippet: studio-rpc-usb-uart
    shield: nice_view
    cmake-args: -DCONFIG_ZMK_STUDIO=y
  - board: corne_choc_pro_right
    shield: nice_view
    snippet: studio-rpc-usb-uart

  - board: corne_choc_pro_left
    shield: settings_reset
    snippet: studio-rpc-usb-uart
  - board: corne_choc_pro_right
    shield: settings_reset
    snippet: studio-rpc-usb-uart
